//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxPayneKFExporter.rc
//
#define IDD_KF_EXPORTER_DIALOG          101
#define IDC_KF_EXPORTER_GEOMETRY        1001
#define IDC_KF_EXPORTER_SKINNING        1002
#define IDC_KF_EXPORTER_CAMERAS         1003
#define IDC_KF_EXPORTER_ANIMATIONS      1004
#define IDC_KF_EXPORTER_MATERIALS       1005
#define IDC_KF_EXPORTER_LIGHTS          1006
#define IDC_KF_EXPORTER_ENVIRONMENT     1007
#define IDC_KF_EXPORTER_HELPERS         1008
#define IDC_KF_EXPORTER_FLOATING_VERTICES 1010
#define IDC_KF_EXPORTER_HIDDEN_OBJECTS  1011
#define IDC_KF_EXPORTER_COPY_TEXTURES   1013
#define IDC_KF_EXPORTER_SCALE           1014
#define IDC_KF_EXPORTER_RETAIN_HIERARCHIES 1015
#define IDC_KF_EXPORTER_USE_PIVOT       1016
#define IDC_KF_EXPORTER_SAVE_REFS       1017
#define IDC_KF_EXPORTER_MP1             1018
#define IDC_KF_EXPORTER_MP2             1019
#define IDC_KF_EXPORTER_USE_GLOBAL_ANIMATION 1020
#define IDC_KF_EXPORTER_MAINTAIN_MATRIX 1021
#define IDC_KF_EXPORTER_INTERPOLATION_VALUE 1022
#define IDC_KF_EXPORTER_LOOP            1023
#define IDC_KF_EXPORTER_LOOP_INTERP     1024
#define IDC_KF_EXPORTER_LOOP_DEC_FRAME  1025
#define IDC_COMBO2                      1026
#define IDC_KF_EXPORTER_PATHS           1026
#define IDC_KF_EXPORTER_START_FRAME_SPIN_EDIT 1039
#define IDC_KF_EXPORTER_START_FRAME_SPIN 1040
#define IDC_KF_EXPORTER_SCALE_SPIN_EDIT 1041
#define IDC_KF_EXPORTER_SCALE_SPIN      1042
#define IDC_KF_EXPORTER_END_FRAME_SPIN_EDIT 1043
#define IDC_KF_EXPORTER_END_FRAME_SPIN  1044
#define IDC_KF_EXPORTER_MIN_ROT_SPIN_EDIT 1045
#define IDC_KF_EXPORTER_MIN_ROT_SPIN    1046
#define IDC_KF_EXPORTER_MIN_POS_SPIN_EDIT 1049
#define IDC_KF_EXPORTER_MIN_POS_SPIN    1050
#define IDC_KF_EXPORTER_SAMPLE_SPIN_EDIT 1051
#define IDC_KF_EXPORTER_SAMPLE_SPIN     1052
#define IDC_KF_EXPORTER_LOOP_TO_FRAME_SPIN_EDIT 1053
#define IDC_KF_EXPORTER_LOOP_TO_FRAME_SPIN 1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
